config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  devise_for :users

  get 'posts/index'
  get 'posts/show'
  root to: "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	scope :get_by_keyword, ->(keyword){
		keywords = keyword.split("　")
		table_field = Array.new
		table_field = [:shop, :area, :genre]

		cond = nil
		keywords.each{ |word|
			table_field.each{ |field|
				cond = cond ? cond.or(arel_table[field].matches('%'+word+'%')) : arel_table[field].matches('%'+word+'%')
			}
		}
		where(cond)
	}

	scope :get_by_name, ->(shop) {
		where("shop like ?", "%#{shop}%")
	}

	scope :get_by_rate_l, ->(rate_l){
		where('rate_l >= ?', "#{rate_l}")
	}

	scope :get_by_rate_u, ->(rate_u){
		where('rate_u <= ?', "#{rate_u}")
	}

	scope :search_values_or, lambda { |field, values|
    	fields = [fields] if fields.class == Symbol

    	cond = nil
    	values.each { |value| 
    		cond = cond ? cond.or(arel_table[field].matches('%'+value+'%')) : arel_table[field].matches('%'+value+'%')
    	}
    	where(cond)
    }

    paginates_per 10  # 1ページあたり5項目表示
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, length: { maximum: 50 }
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(:back) }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to(:back) }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to(:back) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    if params[:keyword].present?
       @posts = @posts.get_by_keyword params[:keyword]
    end

    if params[:shop].present?
       @posts = @posts.get_by_name params[:shop]
    end

    if params[:area].present?
      @posts = @posts.search_values_or(:area, params[:area])
    end

    if params[:genre].present?
      @posts = @posts.search_values_or(:genre, params[:genre])
    end

    if params[:rate_l].present?
       @posts = @posts.get_by_rate_l params[:rate_l]
    end

    if params[:rate_u].present?
       @posts = @posts.get_by_rate_u params[:rate_u]
    end

    @posts = @posts.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).all
    @comment  = @post.comments.build(user_id: current_user.id) if current_user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post][:area] = params[:area].join('/')
      params[:post][:genre] = params[:genre].join('/')
      params.require(:post).permit(:shop, :area, :genre, :rate_u, :rate_l, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
        base_title = "周辺飲食店検索（β版）" # 自分のアプリ名を設定する
        if page_title.empty?
            base_title
        else    
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.hidden_field :user_id %>
<%= f.hidden_field :post_id %>
  <div class="field">
    <%= f.text_area :body, :placeholder => 'コメントを入力...' %>
  </div>
  <div class="actions">
    <%= f.submit 'コメントを書き込む' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <title><%= full_title(yield(:title)) %></title>
	<nav>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <% if user_signed_in? %> 
      <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
      <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "ユーザ登録", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </nav>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="edit">
  <tr>
    <th>店名</th>
    <td><%= f.text_field :shop %></td>
  </tr>
  <tr>
    <th>エリア</th>
    <td>
    <%
    areasInfo = ['八丁堀', '茅場町', '築地' , '銀座', '丸の内', '大手町', '日本橋', '京橋', '有楽町', '日比谷']
    post_area = Array.new
    if @post.area.present?
      post_area = @post.area.split('/')
    end
    
    areasInfo.each do|area|
      checked = ''
      if post_area.include?(area)
        checked = "checked"
      end 
    %>
    <input type="checkbox" value="<%= area %>" name="area[]" <%= checked %> ><%= area %>
    <% end %>
    </td>
  </tr>
  <tr>
    <th>ジャンル</th>
    <td>
    <%
    genresInfo = ['フレンチ', 'イタリアン', '西洋料理', 'カフェ', 'インドカレー', '日本食']
    post_genre = Array.new
    if @post.genre.present?
      post_genre = @post.genre.split('/')
    end

    genresInfo.each do|genre|
      checked = ''
      if post_genre.include?(genre)
        checked = "checked"
      end
    %>
      <input type="checkbox" value="<%= genre %>" name="genre[]" <%= checked %> ><%= genre %>
    <% end %>
    </td>
  </tr>
  <tr>
    <th>価格</th>
    <td>¥<%= f.number_field :rate_l %> 〜 ¥<%= f.number_field :rate_u %></td>
  </tr>
  <tr>
    <th>食べログURL</th>
    <td><%= f.text_field :url %></td>
  </tr>
  </table>
  <br />
  <div class="actions">
  <% if @post.shop.present? %>
    <%= f.submit '店舗情報の更新' %>
  <% else %>
    <%= f.submit '店舗情報の追加' %>
  <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "『"+@post.shop+"』の編集") %>

<h1>店舗情報の編集</h1>

<%= render 'form' %>

<%= link_to '店舗情報', @post %> |
<%= link_to 'TOPに戻る', posts_path %>

app/views/posts/index.html.erb
<% provide(:title, "店舗一覧") %>

<form>
キーワード：<%= text_field_tag :keyword, params[:keyword] %><br />
店名　　　：<%= text_field_tag :shop, params[:shop] %><br />
エリア　　：
<%
  areasInfo = ['八丁堀', '茅場町', '築地' , '銀座', '丸の内', '大手町', '日本橋', '京橋', '有楽町', '日比谷']
  areasInfo.each do|area|
    checked = ''
    if params[:area].present? && params[:area].include?(area)
      checked = 'checked'
    end
%>
    <input type="checkbox" value="<%= area %>" name="area[]" <%= checked %>><%= area %>
<% end %>
<br />
ジャンル　：
<%
  genresInfo = ['フレンチ', 'イタリアン', '西洋料理', 'カフェ', 'インドカレー', '日本食']
  genresInfo.each do|genre|
    checked = ''
    if params[:genre].present? && params[:genre].include?(genre)
      checked = 'checked'
    end
%>
    <input type="checkbox" value="<%= genre %>" name="genre[]" <%= checked %>><%= genre %>
<% end %>
<br />
価格　　　：¥ <%= number_field_tag :rate_l, params[:rate_l] %> 〜 ¥ <%= number_field_tag :rate_u, params[:rate_u] %>
<br />
<input type="submit" value="検索" style="margin:10px 0px 10px; ">
</form>
<hr />

<%= page_entries_info @posts %>
<br /><br />

<table class="shops">
  <thead>
    <tr>
      <th width="30%">店名</th>
      <th width="20%">エリア</th>
      <th width="20%">ジャンル</th>
      <th width="20%">価格</th>
      <th colspan="2" width="10%"><th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= link_to post.shop, post.url %>
        </td>
        <td><%= post.area %></td>
        <td><%= post.genre %></td>
        <td>
        <% if post.rate_l.present? %>¥<%= post.rate_l %><% end %>       
        <% if post.rate_l.present? || post.rate_u.present? %> 〜 <% end %>
        <% if post.rate_u.present? %>¥<%= post.rate_u %><% end %>
        </td> 
        <td><%= link_to '詳細', post %></td>
        <% if user_signed_in? %>
        <td><%= link_to '編集', edit_post_path(post) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<center>
<%= paginate @posts, outer_window: 4 %>
</center>

<br>
<% if user_signed_in? %>
<%= link_to '新しい店を登録する', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<% provide(:title, "新しい店を追加する") %>
<h1>新しい店を追加する</h1>

<%= render 'form' %>

<%= link_to 'TOPに戻る', posts_path %>

app/views/posts/show.html.erb
<% provide(:title, "『"+@post.shop+"』の店舗情報") %>

<% if user_signed_in? %>
<%= link_to '店舗情報の編集', edit_post_path(@post) %> |
<% end %>
<%= link_to 'TOPに戻る', posts_path %>
<br /><br />
<table class="show">
  <tr>
    <th>店名</th>
    <td><%= @post.shop %></td>
  </tr>
  <tr>
    <th>エリア</th>
    <td><%= @post.area %></td>
  </tr>
  <tr>
    <th>ジャンル</th>
    <td><%= @post.genre %></td>
  </tr>
  <tr>
    <th>価格</th>
    <td>
    <% if @post.rate_l.present? %>¥<%= @post.rate_l %><% end %> 
    <% if @post.rate_l.present? || @post.rate_u.present? %> 〜 <% end %>
    <% if @post.rate_u.present? %>¥<%= @post.rate_u %><% end %>
    </td>
  </tr>
  <tr>
    <th>食べログURL</th>
    <td><%= link_to @post.url, @post.url %></td>
  </tr>
</table>

<br />
<h3>【みんなの書き込み】</h3>
<div>
  <% if user_signed_in? %>
    <%= render 'comments/form' %><br />
  <% end %>
  <% if @comments.present? %>
  <% @comments.each do |comment| %>
    <div class="comment">
      <div class="commentContents">
        <% if comment.user.present?
            commenter = comment.user.name
          else
            commenter = '削除されたユーザー'
          end
        %>
        <p><small>投稿者：<%= commenter %></small></p>
        <p><%= comment.body %></p>
        <% if user_signed_in? && comment.user == current_user %>
        <div style="text-align:right;"><small><%= link_to 'コメント削除', comment_path(comment), method: :delete %></small></div>
        <% end %>
      </div>
    </div>
  <% end %>
  <% else %>
  =======================書き込みなし =======================
  <% end %>
</div>